sudo: required 
language: node_js
node_js:
    - "stable"
    
services: 
    - docker

before_install: 
    - docker build -t spolyniak/test-docker-app -f Dockerfile.dev .

.script:     
- docker run -e CI=true spolyniak/test-docker-app npm run test -- --coverage

deploy: 
    provider: elasticbeanstalk
    region: "us-west-2" 
    app: "test-docker-app" 
    env: "Testdockerapp-env" 
    bucket_name: "elasticbeanstalk-us-west-2-979723554484" 
    bucket_path: "test-docker-app" 
    on:
        branch: master 
    access_key_id: $AWS_ACCESS_KEY 
    secret_access_key:
        secure: $AWS_SECRET_KEY